import XCTest

final class ToolStatusCopyTests: XCTestCase {
    func testToolPanelsUseSharedStatusFormatter() throws {
        let source = try readSource("Features/Native/Tools/ToolPanels.swift")
        let advancedSource = try readSource("Features/Native/Tools/ToolAdvancedPanels.swift")
        let completionSource = try readSource("Features/Native/Tools/ToolCompletionPanels.swift")
        let webDigestSource = try readSource("Features/Native/Tools/WebDigestPanel.swift")

        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.waitingToInput(\"JSON\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.waitingToInput(\"文本\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.waitingToImport(\"SRT\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.processingText"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.clipboardLoadedText"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.noClipboardText()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.clipboardEmpty()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.enterInput(\"JSON\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.enterInput(\"文本\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.enterInput(\"要替换的内容\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.enterInput(\"要删除的关键词\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.jsonFormatted(pretty:"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.base64Encoded()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.base64DecodedText()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.base64DecodedHex()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.nothingToCopy(\"结果\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.copied(\"结果\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.saved(\"Markdown\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.decodeFailed()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.invalidBase64()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.nonUTF8ShownAsHex()"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.markdownCleanedSummary("))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.deletedSubtitleSummary(keyword:"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.deletedSubtitle(index:"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.nothingToCopy(\"摘要\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.nothingToCopy(\"差异\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.completed(\"文本对比\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.noContentToGenerate(\"字幕\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.noMatchFound(\"字幕\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.noSubtitleMatch(keyword)"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.deleted(\"字幕\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.restored(\"原始字幕\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.generated(\"FCPXML\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.nothingToCopy(\"内容\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.generatedFCPXMLSummary(subtitleCount:"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.loadedCount(subtitles.count, noun: \"字幕\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.copiedToClipboard(\"FCPXML\")"))
        XCTAssertTrue(source.contains("ToolStatusLabelFormatter.saveFailed(error.localizedDescription)"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.promptToSelect(\"文档\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.promptToSelect(\"图片或从剪贴板识别\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.promptToSelect(\"图片\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.promptToSelect(\"文件夹\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.processingText"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.selectedWaiting(\"文件\", waitingFor: \"转换\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.selectedWaiting(\"图片\", waitingFor: \"识别\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.importedWaiting(\"剪贴板图片\", waitingFor: \"处理\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.emptyState(\"文件夹\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.conflictState(\"命名\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.savedTo(url.lastPathComponent)"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.copiedText()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.selectedRunning(\"文件夹\", action: \"读取文件\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.completed(\"图片处理\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.failed(\"读取文件夹\")"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.noClipboardImage()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.chooseImage()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.ocrCompleted()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.noRecognizedResults()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.recognizedResultsCopied()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.recognizedResultsSaved()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.imageProcessed()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.chooseFolder()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.noRenamableItems()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.duplicateTargetNames()"))
        XCTAssertTrue(advancedSource.contains("ToolStatusLabelFormatter.batchRenameCompleted()"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.running(\"抓取网页资源\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.invalidURL(\"URL\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.missingTool(\"yt-dlp\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.completed(\"批量下载\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.copied(\"摘要\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.copied(\"文件路径\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.downloadCompleted(\"视频\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.noItemsAvailable(\"提供商\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.copied(\"结果\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.saved(\"结果\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.saveFailed(error.localizedDescription)"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.completed(\"对话验证\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.passed(\"连通检查\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.fetched(\"模型列表\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.failed(\"下载\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.loadedCount"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.fallbackText(value:"))
        XCTAssertTrue(completionSource.contains("SettingsStatusLabelFormatter.unconfiguredModelText"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.availabilityState"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.invalidInput(\"网页地址\")"))
        XCTAssertTrue(completionSource.contains("ToolStatusLabelFormatter.invalidInput(\"视频地址\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.waitingToInput(\"URL\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.running(\"调用 defuddle\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.completed(\"生成 Markdown\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.invalidInput(\"网址\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.noContentAvailable(\"正文\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.convertedToMarkdown(\"网页\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.nothingToCopy(\"Markdown\")"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.copiedMarkdown()"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.savedTo(url.lastPathComponent)"))
        XCTAssertTrue(webDigestSource.contains("ToolStatusLabelFormatter.saveFailed(error.localizedDescription)"))
    }

    private func readSource(_ relativePath: String) throws -> String {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let url = repoRoot.appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
